In [4]:
import numpy as np

a = [1,2,3,4,5]
b = np.array(a)

print(type(a))
print(a)
print('-------------------------')
print(type(b))
print(b)

<class 'list'>
[1, 2, 3, 4, 5]
-------------------------
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [8]:
print(a[0])
print(b[0])

print(a[0:3])
print(b[0:3])


1
1
[1, 2, 3]
[1 2 3]


In [10]:
# 덧셈 연산
print(a+a)
print(b+b)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [13]:
print(b)
print(b+2)
print(b/2)
print(b//2)

[1 2 3 4 5]
[3 4 5 6 7]
[0.5 1.  1.5 2.  2.5]
[0 1 1 2 2]


In [14]:
import pandas as pd

a = pd.Series([1,2,3,4,5])
print(a)
print(type(a))



0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [15]:
# 인덱스를 따로지정
a = pd.Series([1,2,3,4], index = ['a','b','c','d'])
print(a)


a    1
b    2
c    3
d    4
dtype: int64


In [19]:
# dict -> Series
a = pd.Series({'a' : 1,'b' : 2,'c' : 3})
print(a)

a    1
b    2
c    3
dtype: int64


In [20]:
a = pd.Series({'a'[1,1,1], 'b'[2,2,2], 'c'[3,3,3]})
b = pd.DataFrame({'a'[1,1,1], 'b'[2,2,2], 'c'[3,3,3]})

print(type(a))
print(a)
print('----------------------------------')
print(type(b))
print(b)

<>:1: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?


TypeError: string indices must be integers

In [21]:
b['b'] = [3,4,5]
print(b)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
#sum
print(b.sum())

In [22]:
# 장르분리

genre = []

for i in data['genres']:
    genre.extend(i.split('|'))

print(len(genre))

NameError: name 'data' is not defined